modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/evanbones/Spiced-Cider/issues"
accessTransformer="META-INF/accesstransformer.cfg"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "${mod_id}.png"
credits = "${mod_credits}"
authors = "${mod_author}"
description = '''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "tide"
type = "optional"
versionRange = "[2.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "caverns_and_chasms"
type = "optional"
versionRange = "[3.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "yet_another_config_lib_v3"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "blockbox"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "everycomp"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "moonlight"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "environmental"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "vanillabackport"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "hominid"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "quark"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "spelunkery"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "slime_time"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "modernworldcreation"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "jade"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${ mod_id }]]
modId = "sodium"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${ mod_id }]]
modId = "vista"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${ mod_id }]]
modId = "snowyspirit"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "CLIENT"
