name = "Spiced Cider"
author = "Evan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc9c1d376b5248c2419c8994b0964740d7c9e7c8ae27a7133bf4c1ed4a302bd1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21–1.21.1"]
