name = "Spiced Cider"
author = "Evan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "117b4c5d28c8681f51c6b9e4f981377c13516badfa209b0449aff66e963268a7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21–1.21.3"]
