name = "Spiced Cider"
author = "Evan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43526f1c22146c2adee891d34ba4b336ad97da7d08c8e9d2216abb48884d62f8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21–1.21.1"]
