# default: 0
renameCost = 0
# default: true
renameCostPerWholeStack = true
# default: true
dropNameTagsOnDeath = true
# default: true
dropNameTagsOnNameChange = true
# default: true
enableNameTagShearing = true
# default: true
enableRenameScreen = true
# default: true
enableCraftingRecipe = true
denylist = []
