enabled = true
disableInCreative = true
enableFluidDiscovery = true
enableEffectDiscovery = true
filterIndex = true
displayCraftableInIndex = true
requireWorkstationForCraftable = true
hideEmptyRemiTabs = true
displayWithUnknownWorkstation = false
exemptInventoryCrafting = true
requireCatalystsKnown = true
allowRecipeLookupForUndiscovered = true
allowUsageLookupForUndiscovered = false
blackoutUnknownInRecipes = true
obscureTooltips = true
showQuestionMarkOverlay = true
enableAdvancementDiscovery = true
