#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

		[types.cake.bountifulfares]
			coconut_cake = true
			cocoa_cake = true
			sponge_cake = true

		[types.cake.nomansland]
			fruit_cake = true

		[types.cake.neapolitan]
			vanilla_cake = true
			chocolate_cake = true
			strawberry_cake = true
			banana_cake = true
			mint_cake = true
			adzuki_cake = true

		[types.wood_type.abundant_atmosphere]
			red_bamboo = true
			ashroot = true
			gourdrot = true

		[types.wood_type.caverns_and_chasms]
			azalea = true

		[types.wood_type.quark]
			azalea = false
			ancient = false
			blossom = false

		[types.wood_type.bountifulfares]
			hoary = true
			walnut = true

		[types.wood_type.nomansland]
			pine = true
			maple = true
			walnut = true
			willow = true

		[types.wood_type.infernalexp]
			luminous = true

		[types.wood_type.arts_and_crafts]
			cork = true

		[types.wood_type.environmental]
			willow = false
			pine = true
			plum = false
			wisteria = true

		[types.wood_type.upgrade_aquatic]
			driftwood = true
			river = true

		[types.wood_type.autumnity]
			maple = false

		[types.wood_type.newworld]
			fir = true

		[types.leaves_type.quark]
			ancient = false
			blue_blossom = false
			lavender_blossom = false
			orange_blossom = false
			yellow_blossom = false
			red_blossom = false

		[types.leaves_type.abundant_atmosphere]
			ashroot = true
			gourdrot = true

		[types.leaves_type.bountifulfares]
			apple = true
			flowering_apple = true
			orange = true
			flowering_orange = true
			lemon = true
			flowering_lemon = true
			plum = true
			flowering_plum = true
			hoary = true
			walnut = true
			golden_apple = true
			flowering_golden_apple = true

		[types.leaves_type.nomansland]
			yellow_birch = true
			autumnal_oak = true
			pale_cherry = true
			frosted = true
			pine = true
			maple = true
			red_maple = true
			walnut = true
			willow = true
			apple_fruit = true
			pear_fruit = true

		[types.leaves_type.arts_and_crafts]
			cork = true

		[types.leaves_type.environmental]
			hibiscus = true
			willow = true
			pine = true
			plum = true
			cheerful_plum = true
			moody_plum = true
			wisteria = true
			pink_wisteria = true
			blue_wisteria = true
			purple_wisteria = true
			white_wisteria = true

		[types.leaves_type.upgrade_aquatic]
			river = true

		[types.leaves_type.autumnity]
			maple = true
			yellow_maple = true
			orange_maple = true
			red_maple = true

		[types.leaves_type.newworld]
			fir = true

		[types.leaves_type.cookscollection]
			lemon = true
			fruiting_lemon = true

		[types.leaves_type.culturaldelights]
			avocado = true
			fruiting_avocado = true

#Disables specific entries
[entries]

		[entries.wood_type.nomansland]
			bookshelf = true
			trimmed_planks = true

		[entries.wood_type.quark]
			vertical_planks = false
			post = false
			trapped_chest = false
			bookshelf = false
			chest = false
			stripped_post = false
			ladder = false
			hollow_log = true
			vertical_slab = false

		[entries.wood_type.shutterup]
			shutter = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.copperagebackport]
			shelf = true

		[entries.wood_type.bountifulfares]
			trellis = true
			pickets = true

		[entries.wood_type.create]
			window = true
			window_pane = true

		[entries.wood_type.boatload]
			large_boat = true
			furnace_boat = true

		[entries.wood_type.woodworks]
			trapped_chest = true
			boards = true
			chest = true
			beehive = true
			bookshelf = false
			chiseled_bookshelf = true
			ladder = true

		[entries.wood_type.valhelsia_structures]
			bundled_stripped_posts = true
			stripped_post = true
			cut_post = true
			bundled_posts = true
			post = true
			cut_stripped_post = true

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = false

		[entries.leaves_type.woodworks]
			leaf_pile = true
