[client]
	#Mobs that can use a youth extender to stop growth let off a buttercup particle when a player holds a youth extender nearby
	"Buttercup particle youth pausation validity indicator" = false
	#Mobs that can use a youth resumer to resume growth let off a buttercup particle when a player holds a youth resumer nearby
	"Buttercup particle youth resumption validity indicator" = false
