#If you have other mods loaded, you might want to make rose gold not that easy to get (for example, Create).
easyCrafting = true
#By default, you can use Rose Gold Ingots to barter with Piglins.
roseGoldBartering = true
