[general]
	#The directory path where assets are exported. Can be relative to the game directory or an absolute path (e.g., C:/Users/Name/Downloads).
	exportDirectory = "C:/Users/evan/Documents/GitHub/Spiced-Cider/pack/resourcepacks/spicedcider_resources"
